### PR TITLE
Demuxer: emit an error in case of unknown data packets and EOF

### LINKED ISSUE #26: demuxer.NextData returns (nil, nil) on unknown data types
This was a bit unexpected and I'm not sure if it was the desired/designed behavior?

I would have expected perhaps to receive a special error for unknown data, or simply have it skipped.

For example, SCTE35 tables are not understood and so this returns `(nil, nil)`:

```go
func TestDemuxerNextDataSCTE35(t *testing.T) {
	scte35 := hexToBytes(`4741f61900fc302500000003289800fff01405000002547fefff4fc614f8
fe00a4e9f50000000000000c1324f6ffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffff`)
	r := bytes.NewReader(scte35)
	assert.Equal(t, 188, r.Len())

	dmx := NewDemuxer(context.Background(), r, DemuxerOptPacketSize(188))
	dmx.programMap.set(502, 1)

	d, err := dmx.NextData()
	assert.NoError(t, err)
	assert.NotNil(t, d)
	assert.Equal(t, uint16(502), d.FirstPacket.Header.PID)
	//assert.NotNil(t, d.SCTE35)
}
```

Similar behavior is also seen on #25 for PMT tables other than program_map

### PR DESCRIPTION
**Pull request by aler9**
Fixes #26 

Fixes  https://github.com/aler9/rtsp-simple-server/issues/558

At the moment, demuxer's `NextData()` returns `(nil, nil)` when the stream is finished (EOF), there are TS packets in the queue but they're unknown data packets (not PSI or PES).

This is due to the fact that `err` is overridden by a call to `parseData()`, that sets it to `nil` unless there's a parse error.

In my opinion, the function:

* should return  `(nil, ErrNoMorePackets)` in case there are TS packets with payload in the queue but they can't be parsed.
* should return `(data, nil)` in case the TS packets in the queue are known data packets

This patch fixes the issue.

### CODE REVIEW

File: demuxer.go [hunk 1]
```diff
@@ -119,14 +119,16 @@ func (dmx *Demuxer) NextData() (d *DemuxerData, err error) {
 					}
 
 					// Parse data
-					if ds, err = parseData(ps, dmx.optPacketsParser, dmx.programMap); err != nil {
+					var err2 error
```
Comment (asticode) [inline demuxer.go:122]: Could you rename `err2` to `errParseData`?

File: demuxer.go [hunk 2]
```diff
@@ -119,14 +119,16 @@ func (dmx *Demuxer) NextData() (d *DemuxerData, err error) {
...
+					if ds, err2 = parseData(ps, dmx.optPacketsParser, dmx.programMap); err2 != nil {
 						// We need to silence this error as there may be some incomplete data here
 						// We still want to try to parse all packets, in case final data is complete
 						continue
 					}
 
 					// Update data
 					if d = dmx.updateData(ds); d != nil {
+						err = nil
```
Comment (asticode) [inline demuxer.go:131]: Why are you resetting `err` here? 🤔 

imho we still want to return an `ErrNoMorePackets` here so that the developer knows the end of stream has been reached.

File: demuxer_test.go [hunk 3]
```diff
@@ -101,6 +101,27 @@ func TestDemuxerNextData(t *testing.T) {
...
+		HasPayload:                true,
+	}, PacketAdaptationField{}, []byte{0x01, 0x02, 0x03, 0x04}, true)
+	bufWriter.Write(b1)
+
+	// The demuxer must return "no more packets"
+	dmx := NewDemuxer(context.Background(), bytes.NewReader(buf.Bytes()),
+		DemuxerOptPacketSize(188))
+	d, err := dmx.NextData()
+	assert.Equal(t, (*DemuxerData)(nil), d)
+	assert.EqualError(t, err, "astits: no more packets")
```
Comment (asticode) [inline demuxer_test.go:122]: Could you use `ErrNoMorePackets.Error()` instead of `"astits: no more packets"` ?

**Review by asticode — CHANGES_REQUESTED** [review]
Nice catch!

File: demuxer.go (hunk 2 above)
Comment (aler9) [reply demuxer.go:131]: i'm not sure about this, in my opinion a read function should return either `(data, nil)` or `(nil, error)` - in this case, even if we reset the error, it reappears at the next function call and makes the function return `(nil, error)`

Comment (asticode) [reply demuxer.go:131]: I agree with you 👍

**Comment by asticode** [comment]
FYI I've created a `v1.10.0` tag
